### ISSUE TITLE
Tech-stack kiezen

### ISSUE THREAD

**Issue by mcphendriks** [mcphendriks/WOGO-web#2]

**Comment by mcphendriks** [comment]
[Link naar onderzoek tech-stack](https://github.com/fdnd-task/choices-choices-justify-your-tech-stack)

**Comment by mcphendriks** [comment]
- [ ] [User eXperience (UX)](https://github.com/fdnd-task/choices-choices-justify-your-tech-stack/blob/main/docs/INSTRUCTIONS.md#1-user-experience)
- [ ] [Developer eXperience (DX)](https://github.com/fdnd-task/choices-choices-justify-your-tech-stack/blob/main/docs/INSTRUCTIONS.md#2-developer-experience)
- [ ] [Content management eXperience (CX)](https://github.com/fdnd-task/choices-choices-justify-your-tech-stack/blob/main/docs/INSTRUCTIONS.md#3-content-management-experience)
